[pytest]
addopts =
    -q
    --ignore=src/GENERAL/main.py
    --ignore=src/SETUP/SCHEDULER/scheduler_panel_ui.py
    --cov=src
    --cov-branch
    --cov-report=term-missing
testpaths = tests
pythonpath = .
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning

[coverage:run]
branch = True
omit =
    */src/GENERAL/main.py
    src/GENERAL/main.py
    src\GENERAL\main.py
    */src/SETUP/SCHEDULER/scheduler_panel_ui.py
    src/SETUP/SCHEDULER/scheduler_panel_ui.py
    src\SETUP\SCHEDULER\scheduler_panel_ui.py
    src/debug.py
# src/MAIL/messagemail.py
    src/NO_PROJECT/*

[coverage:report]
show_missing = True
skip_covered = False
