[pytest]
addopts =
    -q
    --ignore=SRC/GENERAL/main.py
    --ignore=SRC/SETUP/SCHEDULER/scheduler_panel_ui.py
    --cov-config=pytest.ini
    --cov=SRC
    --cov-branch
    --cov-report=term-missing
testpaths = TESTS
pythonpath = .
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning

[coverage:run]
branch = True
omit =
    */SRC/GENERAL/main.py
    SRC/GENERAL/main.py
    SRC\GENERAL\main.py
    */SRC/SETUP/SCHEDULER/scheduler_panel_ui.py
    SRC/SETUP/SCHEDULER/scheduler_panel_ui.py
    SRC\SETUP\SCHEDULER\scheduler_panel_ui.py
    SRC/debug.py
    # SRC/MAIL/messagemail.py
    SRC/NO_PROJECT/*

[coverage:report]
show_missing = True
skip_covered = False
